FROM golang

# Fetch dependencies
RUN go get github.com/tools/godep

# Add project directory to Docker image.
ADD . /go/src/$GO_BOOTSTRAP_REPO_NAME/$GO_BOOTSTRAP_REPO_USER/$GO_BOOTSTRAP_PROJECT_NAME

ENV USER $GO_BOOTSTRAP_CURRENT_USER
ENV HTTP_ADDR :8888
ENV HTTP_DRAIN_INTERVAL 1s
ENV COOKIE_SECRET $GO_BOOTSTRAP_COOKIE_SECRET

# Replace this with actual PostgreSQL DSN.
ENV DSN $GO_BOOTSTRAP_PG_DSN

WORKDIR /go/src/$GO_BOOTSTRAP_REPO_NAME/$GO_BOOTSTRAP_REPO_USER/$GO_BOOTSTRAP_PROJECT_NAME

RUN godep go build

EXPOSE 8888
CMD ./$GO_BOOTSTRAP_PROJECT_NAME