#!/usr/bin/env bash

echo "Creating database $GO_BOOTSTRAP_PROJECT_NAME..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database $GO_BOOTSTRAP_PROJECT_NAME-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on $GO_BOOTSTRAP_PG_TEST_DSN..."
pgmgr -c ".pgmgr.test.json" db migrate
